### ISSUE TITLE
Newer weblogo breaks deduplicate.py

### ISSUE THREAD

**Issue by s-andrews** [peterch405/BabrahamLinkON#2]
The name of the main weblogo lib was changed from weblogolib to just weblogo so if you install a new version of weblogo then it breaks deduplicate.py

```
$ deduplicate.py --help
PuTTY X11 proxy: unable to connect to forwarded X server: Network error: Connection refused
Traceback (most recent call last):
  File "/bi/apps/BabrahamLinkON/latest/bin/deduplicate.py", line 40, in <module>
    from babrahamlinkon import general, presets, umi_correction, UMI_seqlogo, deduplication_general
  File "/bi/apps/python/3.9.7/lib/python3.9/site-packages/babrahamlinkon/UMI_seqlogo.py", line 21, in <module>
    from weblogolib import *
ModuleNotFoundError: No module named 'weblogolib'
```

The fix is to change ```UMI_seqlogo.py``` from:

```from weblogolib import *```

to

```from weblogo import *```

**Comment by peterch405** [comment]
Fixed in f903c34 commit
